# Generated by Django 5.0 on 2023-12-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_like_is_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_like',
        ),
    ]
